INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (1, 'user', '1234');

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (1, 'Sifi');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (2, 'Drama');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (3, 'Romance');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (4, 'Action');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (5, 'Y');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (6, 'Fantasy');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (7, 'Horror');

INSERT INTO BOOK (BOOK_ID, BOOK_NAME, BOOK_DESC, BOOK_PRICE, CATEGORY_ID) VALUES (1, 'Jaomingjo', 'Jao and ming try to survive in fantasy world.','150', 5);
INSERT INTO BOOK (BOOK_ID, BOOK_NAME, BOOK_DESC, BOOK_PRICE, CATEGORY_ID) VALUES (2, 'Kangarookiller', 'The killer that wear kangaroo mask','150', 7);
INSERT INTO BOOK (BOOK_ID, BOOK_NAME, BOOK_DESC, BOOK_PRICE, CATEGORY_ID) VALUES (3, 'Chinese in to the multiverse', 'What will china be with another possible way','100', 1);
INSERT INTO BOOK (BOOK_ID, BOOK_NAME, BOOK_DESC, BOOK_PRICE, CATEGORY_ID) VALUES (4, 'Ghost friends', 'When he died he never go anywhere','100', 6);
INSERT INTO BOOK (BOOK_ID, BOOK_NAME, BOOK_DESC, BOOK_PRICE, CATEGORY_ID) VALUES (5, 'Titangasm', 'The story about titan','150', 4);
INSERT INTO BOOK (BOOK_ID, BOOK_NAME, BOOK_DESC, BOOK_PRICE, CATEGORY_ID) VALUES (6, 'Love at work', 'Stories about love at work from people','100', 3);
INSERT INTO BOOK (BOOK_ID, BOOK_NAME, BOOK_DESC, BOOK_PRICE, CATEGORY_ID) VALUES (7, 'Gun and run', 'The action story that the boy figth until he become majesty','70', 4);
INSERT INTO BOOK (BOOK_ID, BOOK_NAME, BOOK_DESC, BOOK_PRICE, CATEGORY_ID) VALUES (8, 'Friend zone forever', 'This is story that make from a real experence of Pheerapol','200', 2);

INSERT INTO RENTAL (RENTAL_ID, BOOK_ID, USER_ID) VALUES (1, 1, 1);